#!/bin/bash
# Use this file on a unix system to generate the zip archive for CTAN
# ctanify is part of TeX Live distributions
#
ctanify emisa.ins emisa.pdf README.md manifest.txt "emisa-author-template.tex=doc/latex/emisa" "emisa-issue-template.tex=doc/latex/emisa" "emisa.bbx=tex/latex/emisa" "emisa.cbx=tex/latex/emisa" "vector.pdf=doc/latex/emisa" "figure.pdf=doc/latex/emisa" "bitmap.jpg=doc/latex/emisa"
